### ISSUE TITLE
Drop support for PHP 7

### ISSUE THREAD

**Issue by adevade** [adevade/seconds#5]
PHP 7.4 reaches EOL this year. Bump the Composer dependency to only `^8`.

**Comment by karate** [comment]
Hello. I can do this.

**Comment by adevade** [comment]
@karate Are you registered for [Hacktoberfest](https://hacktoberfest.com)? If so I'll wait to merge your PRs until tomorrow or Sunday, so they count towards your goal. 🙂

**Comment by karate** [comment]
Yes, I am. Thank you so much!

**Comment by adevade** [comment]
Actually, reading the [participation rules](https://hacktoberfest.com/participation/#pr-mr-details) again it seems like you must create the PRs after the 1st of October. 

![Screenshot_20220930-134644.png](https://user-images.githubusercontent.com/1066486/193263216-59daf0b4-cbd7-41e1-a3ad-33ef4af67156.png)

So you might want to close them, and submit them again tomorrow or Sunday 👍

**Comment by karate** [comment]
I'm recreating the PRs now. I think it's already October somewhere in UTC+10
